# Generated by Django 4.2.5 on 2023-10-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0002_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="actual_return_date_not_before_borrow_date",
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(("actual_return_date__gte", models.F("borrow_date"))),
                name="actual_return_date_not_before_borrow_date",
            ),
        ),
    ]
